# Generated by Django 3.2 on 2024-01-07 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_rename_ended_at_challenge_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='ended',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='fighting',
            field=models.ManyToManyField(related_name='challgege_fighting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='fire',
            field=models.ManyToManyField(related_name='challgege_fire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='good',
            field=models.ManyToManyField(related_name='challgege_good', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='heart',
            field=models.ManyToManyField(related_name='challgege_heart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='mark',
            field=models.ManyToManyField(related_name='challgege_mark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='question',
            field=models.ManyToManyField(related_name='challgege_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
